name: main

on:
  push:
    branches:
    - main

jobs:
  rust:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      CARGO_TERM_COLOR: always

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install cargo-all-features
    - run: cargo clippy --all-features
    - run: cargo build-all-features
    - run: cargo test-all-features
    - run: ./bin/check.sh
